### ISSUE TITLE
worker1_zone_id variable not working?

### ISSUE THREAD

**Issue by stefancoe** [psrc/urbansim2#114]
@hanase I am not sure if this variable in [variables_households]( https://github.com/psrc/urbansim2/blob/master/psrc_urbansim/vars/variables_households.py) is set up right:
`@orca.column('households', 'worker1_zone_id', cache=True)
def worker1_zone_id(households, persons):
    return misc.reindex(persons.workplace_zone_id[persons.worker1==True], households.building_id).fillna(-1)`

I looked at the [reindex function](https://github.com/UDST/urbansim/blob/master/urbansim/utils/misc.py) and the first series gets joined to the second series on its index, which in this case is person_id (because it is the index on the persons table). It is joined to the second series on it's series values, which in this case is building_id. 

I have not come up with an elegant solution around this since the correct field for the second series would be household_id, which is actually the index of the households table and so is not available as a series to pass into the function. I tried to use the .to_frame method on households so I could reset the index, but that caused an error. Also, since the index on persons is person_id, this needs to be re-indexed to households. You can see my in-elegant solution on this [commit](https://github.com/psrc/urbansim2/commit/ded210392f1bfacabb9383b633f1c44fdb98ee75), which does work. The good news is that I was able to get the hlcm to estimate using a few variables. 

As always, thanks for all your help!

**Comment by hanase** [comment]
You're right, Stefan, the variable is wrong - great catch! There are two common operations, one solved via reindex (in Opus we called it disaggregation, i.e. from an aggregated dataset to a disaggregated one, e.g. disaggregating faz_id from fazes to parcels). The other operation is the opposite, namely aggregating from a lower to a higher aggregated dataset, e.g. number of households from buildings to fazes. For that we use groupby (there are some examples [here](https://github.com/psrc/urbansim2/blob/master/psrc_urbansim/vars/variables_zones.py)). In the case you found, these two cases got mixed up. The implementation tries to disaggregate from a lower to a higher-level dataset which is wrong. 

I think we could use groupby in this case. We could create an array (on persons level) with zone_id where persons are worker1 with a job, otherwise 0. Since that array should have no more than one non-zero value per household, we could just sum those values over all persons per household. It could look something like this (but I haven't tested it):

```
((persons.worker1)*(persons.workplace_zone_id)).\
groupby(persons.household_id).sum().\
reindex(households.index).fillna(-1).replace(0, -1)
```

The last two operations assure a negative value for households with no worker1 with a job. 
What do you think?

**Comment by stefancoe** [comment]
Fantastic! That's much better than my attempt! It works with no modifications.

**Comment by stefancoe** [comment]
[Closed](https://github.com/psrc/urbansim2/commit/2d4b6166a885d1a23ca3551b49b6676dcf9b5c54)
