### ISSUE TITLE
ELCM not finding locations for all jobs because developer model not running

### ISSUE THREAD

**Issue by stefancoe** [psrc/urbansim2#127]
ELCM results in some jobs not having a building_id because there is not enough capacity. This causes the wplcm to crash since there are records where building_id on the jobs table are -1.  So adding a temporary step to delete these jobs so wplcm can run for testing purposes. This step should be deleted once developer model is running again. The step is called delete_unplaced_jobs in [models.py](https://github.com/psrc/urbansim2/blob/stefan_dev/psrc_urbansim/models.py) and was committed here:

https://github.com/psrc/urbansim2/commit/dd968d6aea53c3558c06f28ad5e9a289b904aa15

**Comment by hanase** [comment]
Stefan, wouldn't it be better to make the wplcm to ignore the unplaced jobs? Even if the developer model is functioning, there could always be a situation when not all jobs can be placed, for example due to insufficient zoning. You don't want the whole simulation to crash. In opus, we have a filter at the beginning of the model that makes the model to consider only placed jobs. Would something like that be possible here?

**Comment by stefancoe** [comment]
Yeah- my initial idea was to add an alts_predict_filters of building_id > 0 to the wplcmcoeff.yaml file, but this does not work because utils.py checks for NANs without the filters applied. But I can filter them out before calling the lcm.
