### ISSUE TITLE
target_units in developer class expects a number- instead being passed a dictionary. 

### ISSUE THREAD

**Issue by stefancoe** [psrc/urbansim2#150]
This is happening because we are now computing net units by building type so we have a dictionary with building type and the number of target units for each type. The problem is this [line](https://github.com/UDST/developer/blob/master/developer/develop.py#L430) in the developer class always evaluates to True, which means that all proposals are built. T

@hanase  do we need to run the developer model separately for each building type to meet the targets?  Or perhaps we are going to add this functionality to PSRCdeveloper?

**Comment by hanase** [comment]
The print warning has been fixed by [this pull request](https://github.com/UDST/developer/pull/66). The selection itself is handled by the `custom_selection_func` which in our case expects a dictionary as target units. The goal is to run only one developer for all building types, regardless if it is residential or non-residential.
